insert into categorias (descripcion) values('Desarrollo Web');
insert into categorias (descripcion) values('Desarrollo Móvil');
insert into categorias (descripcion) values('Programación General');
insert into categorias (descripcion) values('Bases de datos');
insert into roles(descripcion) values('user');
insert into usuarios (username,password,email,nombre,apellidos,rol) values('juanito','$2y$12$VN6XUZmvVivo2FRCnOCXwuKMWAjnjN5ZwpYFAHGZdVche9nvXEvw6 ','juanito@gmail.com','Juanito','Sanchez Garcia',1);
insert into usuarios (username,password,email,nombre,apellidos,rol) values('pepito','$2y$12$VN6XUZmvVivo2FRCnOCXwuKMWAjnjN5ZwpYFAHGZdVche9nvXEvw6 ','pepitoperez@gmail.com','Pepito','Perez Sánchez',1);
insert into posts(titulo,descripcion,contenido,idusuario,idcategoria,created_at) values ('Post de prueba','Hola esto es un post de prueba','contenido',1,1,CURRENT_TIMESTAMP);
insert into posts(titulo,descripcion,contenido,idusuario,idcategoria,created_at) values ('Post de prueba 2','Hola esto es otro post de prueba','contenido',1,1,CURRENT_TIMESTAMP);
insert into posts(titulo,descripcion,contenido,idusuario,idcategoria,created_at) values ('Post de prueba 3','Hola esto es otro post de prueba 3','contenido',1,2,CURRENT_TIMESTAMP);
insert into posts(titulo,descripcion,contenido,idusuario,idcategoria,created_at) values ('Post de pepito','Hola esto es el post de pepito','aaabb',2,1,CURRENT_TIMESTAMP);
insert into tags values(1,'Java');
insert into tags values(2,'JavaScript');
insert into tags values(3,'VUE');
insert into posts_tags values(1,1);
insert into posts_tags values(2,2);
insert into posts_tags values(2,3);
insert into posts_tags values(3,1);
insert into posts_tags values(4,2);
insert into posts_tags values(4,3);
insert into comentarios(idusuario,idpost,contenido) values(1,2,'¡Increible!');